/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OFGraph;

import java.net.UnknownHostException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Dr. Greg M. Bernstein, modified by 164776
 */
public class VertexPropertyDialog extends javax.swing.JDialog {

    GraphElements.MyVertex vertex;

    /**
     * Creates new form VertexPropertyDialog
     * @param parent The parent JFrame.
     * @param vertex A given vertex.
     */
    public VertexPropertyDialog(java.awt.Frame parent, GraphElements.MyVertex vertex) {
        super(parent, true);
        this.vertex = vertex;
        initComponents();
        this.setTitle(vertex.getType() + ": " + vertex.getName());
        this.hostFormattedTextField.setValue(vertex.getName());
        this.ipFormattedTextField.setValue(vertex.getIPtoString());
        this.macFormattedTextField.setValue(vertex.getMAC());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        String _255 = "(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)";
        Pattern p = Pattern.compile( "^(?:" + _255 + "\\.){3}" + _255 + "$");
        RegexFormatter ipFormatter = new RegexFormatter(p);
        ipFormattedTextField = new javax.swing.JFormattedTextField(ipFormatter);
        macFormattedTextField = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        hostFormattedTextField = new javax.swing.JFormattedTextField(new String());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edge Properties");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonHandler(evt);
            }
        });

        jLabel1.setText("IP Address:");

        jLabel2.setText("MAC Address:");
        if (vertex.getType().equals("Switch")) {
            jLabel2.setText("DPID:");
        }

        if (vertex.getType().equals("Host")) {
            try {
                macFormattedTextField = new javax.swing.JFormattedTextField(
                    new MaskFormatter("HH:HH:HH:HH:HH:HH"));
            }
            catch (ParseException e) {
                e.printStackTrace();
            }
        } else { //if (vertex.getType().equals("Switch")
            try {
                macFormattedTextField = new javax.swing.JFormattedTextField(
                    new MaskFormatter("HH:HH:HH:HH:HH:HH:HH:HH"));
            }
            catch (ParseException e) {
                e.printStackTrace();
            }
        }

        jLabel3.setText("Rename " + vertex.getType() + ": ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(hostFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jButton1)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel2))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(macFormattedTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .add(ipFormattedTextField)))))
                    .add(layout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(hostFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(ipFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(macFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonHandler
        vertex.setName((String) this.hostFormattedTextField.getValue());
        try {
            vertex.setIP((String) this.ipFormattedTextField.getValue());
        } catch (UnknownHostException ex) {
            Logger.getLogger(VertexPropertyDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        vertex.setMAC((String) this.macFormattedTextField.getValue());

        dispose();
    }//GEN-LAST:event_okButtonHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField hostFormattedTextField;
    private javax.swing.JFormattedTextField ipFormattedTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField macFormattedTextField;
    // End of variables declaration//GEN-END:variables

}
